version: "3.3"
services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: broker
    user: "1000:1000"
    ports:
      - "1883:1883"
    volumes:
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
      - ./broker/config:/mosquitto/config


  server:
    build: ./server
    ports:
      - "2021:2021/udp"
    depends_on:
      - broker

  prediction:
    build: ./prediction
    depends_on:
      - broker
