version: "3.8"
services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
      - ./broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
