version: "3.3"
services:
  broker:
    image: eclipse-mosquitto:latest
      #user: "1000:1000"
    ports:
      - "1883:1883"
    volumes:
      - $PWD/broker/data:/mosquitto/data
      - $PWD/broker/log:/mosquitto/log
      - $PWD/broker/config:/mosquitto/config
  
